createTask:
    path: /tasks
    controller: App\Controller\TaskController::createTask
    methods: POST

displayTasks:
  path: /tasks
  controller: App\Controller\TaskController::getTasks
  methods: GET

displayTask:
  path: /tasks/{id}
  controller: App\Controller\TaskController::getTask
  methods: GET
  requirements:
    id: '\d+'
