parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    TaskService:
        class: App\Services\TaskService
        autowire: true
    App\Controller\:
        resource: '../src/Controller'
        arguments: ['@TaskService']
    App\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
